// Single source of truth for the language dropdown. Kept separate from hljs.js
// so the popup can import the list without bundling all of highlight.js.
export const SUPPORTED_LANGUAGES = [
  { value: 'auto',        label: 'Auto-detect' },
  { value: 'javascript',  label: 'JavaScript' },
  { value: 'typescript',  label: 'TypeScript' },
  { value: 'python',      label: 'Python' },
  { value: 'java',        label: 'Java' },
  { value: 'c',           label: 'C' },
  { value: 'cpp',         label: 'C++' },
  { value: 'csharp',      label: 'C#' },
  { value: 'go',          label: 'Go' },
  { value: 'rust',        label: 'Rust' },
  { value: 'kotlin',      label: 'Kotlin' },
  { value: 'swift',       label: 'Swift' },
  { value: 'php',         label: 'PHP' },
  { value: 'ruby',        label: 'Ruby' },
  { value: 'dart',        label: 'Dart' },
  { value: 'scala',       label: 'Scala' },
  { value: 'r',           label: 'R' },
  { value: 'perl',        label: 'Perl' },
  { value: 'lua',         label: 'Lua' },
  { value: 'objectivec',  label: 'Objective-C' },
  { value: 'powershell',  label: 'PowerShell' },
  { value: 'bash',        label: 'Bash / Shell' },
  { value: 'sql',         label: 'SQL' },
  { value: 'json',        label: 'JSON' },
  { value: 'yaml',        label: 'YAML' },
  { value: 'xml',         label: 'HTML / XML' },
  { value: 'css',         label: 'CSS' },
  { value: 'scss',        label: 'SCSS' },
  { value: 'markdown',    label: 'Markdown' },
  { value: 'dockerfile',  label: 'Dockerfile' },
  { value: 'plaintext',   label: 'Plain text' },
];
